export const products = [
  {
    title: "Savon Citron",
    quantGr: "100",
    textDescription:
      "Authentique et traditionnel, le Savon Citron est enrichi d'huile végétale.",
    arrayCompo: [
      "SODIUM PALMATE",
      "SODIUM PALM KERNELATE",
      "AQUA (WATER)",
      "PARFUM (FRAGRANCE)",
      "PALM ACID",
      "GLYCERIN",
      "LIMONENE",
      "SODIUM CHLORIDE",
      "PALM KERNEL ACID",
      "CITRAL",
      "TETRASODIUM EDTA",
      "ETIDRONIC ACID",
      "HYDROXYCITRONELLAL",
      "CI 11680",
    ],
    price: "3,17",
    img: "/images/05821-small.jpg",
    categorie: "savon_marseille",
    tags: ["huile végétale", "authentique", "citron"],
  },
  {
    title: "Savon Citron",
    quantGr: "125",
    textDescription:
      "Authentique et traditionnel, le Savon Citron est enrichi d'huile végétale.",
    arrayCompo: [
      "SODIUM PALMATE",
      "SODIUM PALM KERNELATE",
      "AQUA (WATER)",
      "PARFUM (FRAGRANCE)",
      "PALM ACID",
      "GLYCERIN",
      "LIMONENE",
      "SODIUM CHLORIDE",
      "PALM KERNEL ACID",
      "CITRAL",
      "TETRASODIUM EDTA",
      "ETIDRONIC ACID",
      "HYDROXYCITRONELLAL",
      "CI 11680",
    ],
    price: "3,22",
    img: "/images/05821-small.jpg",
    categorie: "savon_marseille",
    tags: ["huile végétale", "authentique", "citron"],
  },
  {
    title: "Savon Fraise",
    quantGr: "100",
    textDescription:
      "Authentique et traditionnel, le Savon Fraise est enrichi d'huile végétale.",
    arrayCompo: [
      "SODIUM PALMATE",
      "SODIUM PALM KERNELATE",
      "AQUA (WATER)",
      "PARFUM (FRAGRANCE)",
      "PALM ACID",
      "GLYCERIN",
      "SODIUM CHLORIDE",
      "PALM KERNEL ACID",
      "CITRAL",
      "TETRASODIUM EDTA",
      "ETIDRONIC ACID",
      "HYDROXYCITRONELLAL",
      "CI 11680",
    ],
    price: "3,13",
    img: "/images/05825-small.jpg",
    categorie: "savon_marseille",
    tags: ["huile végétale", "authentique", "fraise"],
  },
  {
    title: "Savon Fraise",
    quantGr: "125",
    textDescription:
      "Authentique et traditionnel, le Savon Fraise est enrichi d'huile végétale.",
    arrayCompo: [
      "SODIUM PALMATE",
      "SODIUM PALM KERNELATE",
      "AQUA (WATER)",
      "PARFUM (FRAGRANCE)",
      "PALM ACID",
      "GLYCERIN",
      "SODIUM CHLORIDE",
      "PALM KERNEL ACID",
      "CITRAL",
      "TETRASODIUM EDTA",
      "ETIDRONIC ACID",
      "HYDROXYCITRONELLAL",
      "CI 11680",
    ],
    price: "3,18",
    img: "/images/05825-small.jpg",
    categorie: "savon_marseille",
    tags: ["huile végétale", "authentique", "fraise"],
  },
  {
    title: "Savon Abricot",
    quantGr: "100",
    textDescription:
      "Authentique et traditionnel, le Savon Abricot est enrichi d'huile végétale.",
    arrayCompo: [
      "SODIUM PALMATE",
      "SODIUM PALM KERNELATE",
      "AQUA (WATER)",
      "PARFUM (FRAGRANCE)",
      "PALM ACID",
      "GLYCERIN",
      "LIMONENE",
      "SODIUM CHLORIDE",
      "PALM KERNEL ACID",
      "CITRAL",
      "TETRASODIUM EDTA",
      "ETIDRONIC ACID",
      "HYDROXYCITRONELLAL",
      "CI 11680",
    ],
    price: "3,11",
    img: "/images/05833-small.jpg",
    categorie: "savon_marseille",
    tags: ["huile végétale", "authentique", "abricot"],
  },
  {
    title: "Savon Abricot",
    quantGr: "125",
    textDescription:
      "Authentique et traditionnel, le Savon Abricot est enrichi d'huile végétale.",
    arrayCompo: [
      "SODIUM PALMATE",
      "SODIUM PALM KERNELATE",
      "AQUA (WATER)",
      "PARFUM (FRAGRANCE)",
      "PALM ACID",
      "GLYCERIN",
      "LIMONENE",
      "SODIUM CHLORIDE",
      "PALM KERNEL ACID",
      "CITRAL",
      "TETRASODIUM EDTA",
      "ETIDRONIC ACID",
      "HYDROXYCITRONELLAL",
      "CI 11680",
    ],
    price: "3,15",
    img: "/images/05833-small.jpg",
    categorie: "savon_marseille",
    tags: ["huile végétale", "authentique", "abricot"],
  },
  {
    title: "Savon Cassis",
    quantGr: "100",
    textDescription:
      "Authentique et traditionnel, le Savon Cassis est enrichi d'huile végétale.",
    arrayCompo: [
      "SODIUM PALMATE",
      "SODIUM PALM KERNELATE",
      "AQUA (WATER)",
      "PARFUM (FRAGRANCE)",
      "PALM ACID",
      "GLYCERIN",
      "SODIUM CHLORIDE",
      "PALM KERNEL ACID",
      "CITRAL",
      "TETRASODIUM EDTA",
      "ETIDRONIC ACID",
      "HYDROXYCITRONELLAL",
      "CI 11680",
    ],
    price: "3,22",
    img: "/images/05821-small.jpg",
    categorie: "savon_leserail",
    tags: ["huile végétale", "authentique", "cassis"],
  },
  {
    title: "Savon Cassis",
    quantGr: "125",
    textDescription:
      "Authentique et traditionnel, le Savon Cassis est enrichi d'huile végétale.",
    arrayCompo: [
      "SODIUM PALMATE",
      "SODIUM PALM KERNELATE",
      "AQUA (WATER)",
      "PARFUM (FRAGRANCE)",
      "PALM ACID",
      "GLYCERIN",
      "SODIUM CHLORIDE",
      "PALM KERNEL ACID",
      "CITRAL",
      "TETRASODIUM EDTA",
      "ETIDRONIC ACID",
      "HYDROXYCITRONELLAL",
      "CI 11680",
    ],
    price: "3,27",
    img: "/images/05821-small.jpg",
    categorie: "savon_leserail",
    tags: ["huile végétale", "authentique", "cassis"],
  },
];
